# Establecer la imagen base
FROM nginx:alpine

# Copiar la carpeta assets al directorio de trabajo de Nginx
COPY assets/ /usr/share/nginx/html/assets

# Copiar la carpeta dist al directorio de trabajo de Nginx
COPY dist/ /usr/share/nginx/html


